lista_preguntas = [
    {"pregunta":"¿En qué ciudad nació Lionel Messi?", "respuesta_1":"Rosario","respuesta_2":"Buenos Aires","respuesta_3":"Córdoba","respuesta_correcta":1},
    {"pregunta": "¿Cuál es la capital de Argentina?", "respuesta_1": "Buenos Aires", "respuesta_2": "Córdoba", "respuesta_3": "Rosario", "respuesta_correcta": 1},
    {"pregunta": "¿En qué año ganó Argentina su primer mundial de fútbol?", "respuesta_1": "1978", "respuesta_2": "1986", "respuesta_3": "2002", "respuesta_correcta": 1},
    {"pregunta": "¿Quién es conocido como el 'Padre de la Patria' en Argentina?", "respuesta_1": "Juan Manuel de Rosas", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el pico más alto de Argentina?", "respuesta_1": "Cerro Aconcagua", "respuesta_2": "Cerro Tronador", "respuesta_3": "Cerro Fitz Roy", "respuesta_correcta": 1},
    {"pregunta": "¿Qué río separa a Argentina de Uruguay?", "respuesta_1": "Río Paraná", "respuesta_2": "Río Colorado", "respuesta_3": "Río de la Plata", "respuesta_correcta": 3},
    {"pregunta": "¿Quién compuso la canción 'Gracias a la Vida'?", "respuesta_1": "Mercedes Sosa", "respuesta_2": "Charly García", "respuesta_3": "Violeta Parra", "respuesta_correcta": 3},
    {"pregunta": "¿En qué año fue elegido presidente Néstor Kirchner?", "respuesta_1": "2000", "respuesta_2": "2003", "respuesta_3": "2007", "respuesta_correcta": 2},
    {"pregunta": "¿En qué provincia se encuentra la ciudad de Ushuaia?", "respuesta_1": "Santa Cruz", "respuesta_2": "Chubut", "respuesta_3": "Tierra del Fuego", "respuesta_correcta": 3},
    {"pregunta": "¿Qué moneda se utiliza en Argentina?", "respuesta_1": "Dólar", "respuesta_2": "Peso", "respuesta_3": "Real", "respuesta_correcta": 2},
    {"pregunta": "¿Qué famoso cantante argentino popularizó el tango?", "respuesta_1": "Astor Piazzolla", "respuesta_2": "Carlos Gardel", "respuesta_3": "Sandro", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la danza tradicional de Argentina?", "respuesta_1": "Salsa", "respuesta_2": "Cumbia", "respuesta_3": "Tango", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el nombre del famoso glaciar en la Patagonia?", "respuesta_1": "Perito Moreno", "respuesta_2": "Martial", "respuesta_3": "Upsala", "respuesta_correcta": 1},
    {"pregunta": "¿Quién es el autor de 'Martín Fierro'?", "respuesta_1": "Jorge Luis Borges", "respuesta_2": "José Hernández", "respuesta_3": "Julio Cortázar", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la montaña más alta de América del Sur?", "respuesta_1": "Cerro Bonete", "respuesta_2": "Monte Pissis", "respuesta_3": "Aconcagua", "respuesta_correcta": 3},
    {"pregunta": "¿Qué bebida es famosa en Argentina?", "respuesta_1": "Tequila", "respuesta_2": "Mate", "respuesta_3": "Pisco", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el nombre del teatro más famoso de Buenos Aires?", "respuesta_1": "Teatro Colón", "respuesta_2": "Teatro Gran Rex", "respuesta_3": "Teatro Nacional", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la Avenida más ancha del mundo ubicada en Buenos Aires?", "respuesta_1": "Avenida de Mayo", "respuesta_2": "Avenida Corrientes", "respuesta_3": "Avenida 9 de Julio", "respuesta_correcta": 3},
    {"pregunta": "¿Qué prócer argentino creó la bandera?", "respuesta_1": "Domingo Sarmiento", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano", "respuesta_correcta": 3},
    {"pregunta": "¿Qué actriz argentina fue esposa de Juan Domingo Perón?", "respuesta_1": "Tita Merello", "respuesta_2": "Eva Perón", "respuesta_3": "Libertad Lamarque", "respuesta_correcta": 2},
    {"pregunta": "¿En qué año fue la Guerra de las Malvinas?", "respuesta_1": "1980", "respuesta_2": "1982", "respuesta_3": "1984", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el nombre del equipo de fútbol conocido como 'La Academia'?", "respuesta_1": "Boca Juniors", "respuesta_2": "Racing Club", "respuesta_3": "River Plate", "respuesta_correcta": 2},
    {"pregunta": "¿En qué provincia se encuentra la ciudad de Mendoza?", "respuesta_1": "Santa Fe", "respuesta_2": "San Juan", "respuesta_3": "Mendoza", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el ave nacional de Argentina?", "respuesta_1": "Cóndor", "respuesta_2": "Ñandú", "respuesta_3": "Hornero", "respuesta_correcta": 3},
    {"pregunta": "¿Qué escritora argentina ganó el Premio Cervantes en 2018?", "respuesta_1": "Silvina Ocampo", "respuesta_2": "María Elena Walsh", "respuesta_3": "María Teresa Andruetto", "respuesta_correcta": 3},
    {"pregunta": "¿Qué ciudad argentina es conocida por sus cataratas?", "respuesta_1": "Misiones", "respuesta_2": "Puerto Iguazú", "respuesta_3": "Cataratas de Córdoba", "respuesta_correcta": 2},
    {"pregunta":"¿Cuál es el plato típico argentino hecho con carne y chimichurri?", "respuesta_1":"Empanadas", "respuesta_2":"Asado", "respuesta_3":"Locro", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'El Aleph'?", "respuesta_1":"Julio Cortázar", "respuesta_2":"Jorge Luis Borges", "respuesta_3":"Ernesto Sábato", "respuesta_correcta":2},
    {"pregunta":"¿Qué provincia argentina es conocida por sus viñedos?", "respuesta_1":"Mendoza", "respuesta_2":"Salta", "respuesta_3":"San Juan", "respuesta_correcta":1},
    {"pregunta":"¿Qué selección le ganó Argentina en la final del Mundial 2022?", "respuesta_1":"Brasil", "respuesta_2":"Francia", "respuesta_3":"Alemania", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso cantante de rock argentino lideró la banda Soda Stereo?", "respuesta_1":"Charly García", "respuesta_2":"Gustavo Cerati", "respuesta_3":"Fito Páez", "respuesta_correcta":2},
    {"pregunta":"¿En qué año se fundó la ciudad de Buenos Aires por primera vez?", "respuesta_1":"1536", "respuesta_2":"1580", "respuesta_3":"1607", "respuesta_correcta":1},
    {"pregunta":"¿Qué presidente argentino fue derrocado en 1955?", "respuesta_1":"Juan Domingo Perón", "respuesta_2":"Arturo Frondizi", "respuesta_3":"Hipólito Yrigoyen", "respuesta_correcta":1},
    {"pregunta":"¿Qué equipo de fútbol tiene el apodo de 'El Millonario'?", "respuesta_1":"Independiente", "respuesta_2":"River Plate", "respuesta_3":"San Lorenzo", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso revolucionario argentino luchó en Cuba?", "respuesta_1":"Manuel Belgrano", "respuesta_2":"Ernesto 'Che' Guevara", "respuesta_3":"Mariano Moreno", "respuesta_correcta":2},
    {"pregunta":"¿Cuál es el nombre del desierto ubicado en la Patagonia?", "respuesta_1":"Desierto de Atacama", "respuesta_2":"Desierto de La Tatacoa", "respuesta_3":"Desierto de la Patagonia", "respuesta_correcta":3},
    {"pregunta":"¿Qué famoso festival de folklore se celebra en Cosquín?", "respuesta_1":"Festival de Cosquín", "respuesta_2":"Festival de Jesús María", "respuesta_3":"Festival de Baradero", "respuesta_correcta":1},
    {"pregunta":"¿Qué jugador argentino es conocido como 'El Apache'?", "respuesta_1":"Carlos Tevez", "respuesta_2":"Diego Maradona", "respuesta_3":"Sergio Agüero", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso científico argentino ganó el Premio Nobel de Medicina en 1984?", "respuesta_1":"Luis Federico Leloir", "respuesta_2":"César Milstein", "respuesta_3":"Bernardo Houssay", "respuesta_correcta":2},
    {"pregunta":"¿Qué provincia argentina es conocida como 'La Tierra del Sol'?", "respuesta_1":"La Rioja", "respuesta_2":"Catamarca", "respuesta_3":"Santiago del Estero", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso grupo musical argentino es conocido por canciones como 'De música ligera'?", "respuesta_1":"Los Fabulosos Cadillacs", "respuesta_2":"Soda Stereo", "respuesta_3":"Enanitos Verdes", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso actor argentino protagonizó 'El secreto de sus ojos'?", "respuesta_1":"Ricardo Darín", "respuesta_2":"Guillermo Francella", "respuesta_3":"Luis Brandoni", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino compuso 'Adiós Nonino'?", "respuesta_1":"Astor Piazzolla", "respuesta_2":"Osvaldo Pugliese", "respuesta_3":"Aníbal Troilo", "respuesta_correcta":1},
    {"pregunta":"¿Cuál es el nombre del famoso estadio de Boca Juniors?", "respuesta_1":"El Monumental", "respuesta_2":"La Bombonera", "respuesta_3":"El Cilindro", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso pintor argentino es conocido por sus obras surrealistas?", "respuesta_1":"Antonio Berni", "respuesta_2":"Xul Solar", "respuesta_3":"Benito Quinquela Martín", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Peludo'?", "respuesta_1":"Hipólito Yrigoyen", "respuesta_2":"Juan Manuel de Rosas", "respuesta_3":"Domingo Faustino Sarmiento", "respuesta_correcta":1},
    {"pregunta":"¿Qué provincia argentina es famosa por sus termas?", "respuesta_1":"Entre Ríos", "respuesta_2":"Corrientes", "respuesta_3":"Misiones", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso poeta argentino escribió 'Veinte poemas de amor y una canción desesperada'?", "respuesta_1":"Pablo Neruda", "respuesta_2":"Octavio Paz", "respuesta_3":"Juan Gelman", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso jugador argentino es conocido como 'El Kun'?", "respuesta_1":"Lionel Messi", "respuesta_2":"Sergio Agüero", "respuesta_3":"Ángel Di María", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Negro'?", "respuesta_1":"Fito Páez", "respuesta_2":"Charly García", "respuesta_3":"Luis Alberto Spinetta", "respuesta_correcta":3},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'Rayuela'?", "respuesta_1":"Julio Cortázar", "respuesta_2":"Adolfo Bioy Casares", "respuesta_3":"Leopoldo Lugones", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino fue líder de Los Abuelos de la Nada?", "respuesta_1":"Andrés Calamaro", "respuesta_2":"Gustavo Cerati", "respuesta_3":"Miguel Mateos", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso actor argentino protagonizó 'Nueve Reinas'?", "respuesta_1":"Ricardo Darín", "respuesta_2":"Guillermo Francella", "respuesta_3":"Diego Peretti", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Restaurador'?", "respuesta_1":"Juan Manuel de Rosas", "respuesta_2":"Domingo Faustino Sarmiento", "respuesta_3":"Bartolomé Mitre", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Flaco'?", "respuesta_1":"Luis Alberto Spinetta", "respuesta_2":"Charly García", "respuesta_3":"Fito Páez", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'Sobre héroes y tumbas'?", "respuesta_1":"Ernesto Sábato", "respuesta_2":"Jorge Luis Borges", "respuesta_3":"Julio Cortázar", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino es conocido como 'El Polaco'?", "respuesta_1":"Rodrigo", "respuesta_2":"Pappo", "respuesta_3":"Palito Ortega", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Padre del Aula'?", "respuesta_1":"Domingo Faustino Sarmiento", "respuesta_2":"Juan Bautista Alberdi", "respuesta_3":"Bartolomé Mitre", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Potro'?", "respuesta_1":"Rodrigo", "respuesta_2":"Alejandro Lerner", "respuesta_3":"Diego Torres", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'Ficciones'?", "respuesta_1":"Julio Cortázar", "respuesta_2":"Jorge Luis Borges", "respuesta_3":"Adolfo Bioy Casares", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso músico argentino es conocido como 'El Carpo'?", "respuesta_1":"Charly García", "respuesta_2":"Luis Alberto Spinetta", "respuesta_3":"Fito Páez", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Chacho'?", "respuesta_1":"Ángel Vicente Peñaloza", "respuesta_2":"Facundo Quiroga", "respuesta_3":"Juan Manuel de Rosas", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Negro' Rada?", "respuesta_1":"Rubén Rada", "respuesta_2":"Jairo", "respuesta_3":"Víctor Heredia", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'El túnel'?", "respuesta_1":"Ernesto Sábato", "respuesta_2":"Julio Cortázar", "respuesta_3":"Jorge Luis Borges", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino es conocido como 'El Zurdo'?", "respuesta_1":"Charly García", "respuesta_2":"Luis Alberto Spinetta", "respuesta_3":"Fito Páez", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Loco'?", "respuesta_1":"Hipólito Yrigoyen", "respuesta_2":"Raúl Alfonsín", "respuesta_3":"Arturo Illia", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Flaco' Spinetta?", "respuesta_1":"Luis Alberto Spinetta", "respuesta_2":"Charly García", "respuesta_3":"Fito Páez", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'Bestiario'?", "respuesta_1":"Julio Cortázar", "respuesta_2":"Jorge Luis Borges", "respuesta_3":"Adolfo Bioy Casares", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino es conocido como 'El Flaco' Gieco?", "respuesta_1":"León Gieco", "respuesta_2":"Víctor Heredia", "respuesta_3":"Mercedes Sosa", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Turco'?", "respuesta_1":"Carlos Menem", "respuesta_2":"Néstor Kirchner", "respuesta_3":"Eduardo Duhalde", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Negro' Ortiz?", "respuesta_1":"Palito Ortega", "respuesta_2":"Víctor Heredia", "respuesta_3":"Jairo", "respuesta_correcta":3},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'La invención de Morel'?", "respuesta_1":"Adolfo Bioy Casares", "respuesta_2":"Julio Cortázar", "respuesta_3":"Ernesto Sábato", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso músico argentino es conocido como 'El Flaco' Suárez?", "respuesta_1":"Gustavo Cerati", "respuesta_2":"Luis Alberto Spinetta", "respuesta_3":"Charly García", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso político argentino fue conocido como 'El Panzer'?", "respuesta_1":"Juan Domingo Perón", "respuesta_2":"Carlos Menem", "respuesta_3":"Raúl Alfonsín", "respuesta_correcta":2},
    {"pregunta":"¿Qué famoso cantante argentino es conocido como 'El Flaco' Baralis?", "respuesta_1":"Jairo", "respuesta_2":"Víctor Heredia", "respuesta_3":"Mercedes Sosa", "respuesta_correcta":1},
    {"pregunta":"¿Qué famoso escritor argentino escribió 'Operación Masacre'?", "respuesta_1":"Rodolfo Walsh", "respuesta_2":"Ernesto Sábato", "respuesta_3":"Julio Cortázar", "respuesta_correcta":1}
]
